"""논리 컬럼명(스킬 산출물 CSV 헤더) → DB 물리 컬럼명(snake_case) 단일 출처.

data-ingestion-backend/docs/DB스키마.md §9(물리 컬럼 매핑, 확정본)를 그대로 옮긴 것이다.
`models.py`(Table 정의)와, 다음 라운드의 `loaders.py`(CSV→DB 적재)가 반드시 이 모듈만 참조한다.
양쪽에 컬럼명 문자열을 중복 정의하지 않는다(§9 규칙).

각 값은 `(논리명, 물리명)` 튜플의 순서 있는 튜플이다 — 순서는 실제 산출물 헤더 순서와 동일하게 유지한다.
"""

from __future__ import annotations

# --- processed_* 6종 (DB스키마.md §9.1~9.6) ---

PROCESSED_FLIGHT_DATA: tuple[tuple[str, str], ...] = (
    ("DATE", "date"),
    ("CALLSIGN", "callsign"),
    ("SSR", "ssr"),
    ("DEPT", "dept"),
    ("DEST", "dest"),
    ("EOBT", "eobt"),
    ("F_TYPE", "f_type"),
    ("ATD", "atd"),
    ("TEET", "teet"),
    ("RFL", "rfl"),
    ("AFL", "afl"),
    ("XFL", "xfl"),
    ("CFL", "cfl"),
    ("A_TYPE", "a_type"),
    ("LINE", "line"),
    ("ENTRY_FIR", "entry_fir"),
    ("ENTRY_DATETIME", "entry_datetime"),
    ("EXIT_FIR", "exit_fir"),
    ("EXIT_DATETIME", "exit_datetime"),
    ("확장루트", "ext_route"),
    ("FULL_ROUTE", "full_route"),
    ("FIR_ENROUTE", "fir_enroute"),
    ("ALT_DEST", "alt_dest"),
    ("고유ID", "unique_id"),
    ("REG NO", "reg_no"),
    ("OTHER", "other"),
)

PROCESSED_ACDM_DEPARTURE: tuple[tuple[str, str], ...] = (
    ("operation_date", "operation_date"),
    ("airport_icao", "airport_icao"),
    ("flight_icao", "flight_icao"),
    ("airline_icao", "airline_icao"),
    ("counterpart_airport_icao", "counterpart_airport_icao"),
    ("aircraft_registration", "aircraft_registration"),
    ("aircraft_type", "aircraft_type"),
    ("domestic_international", "domestic_international"),
    ("stand", "stand"),
    ("gate", "gate"),
    ("runway", "runway"),
    ("flight_status", "flight_status"),
    ("exception_status", "exception_status"),
    ("linked_flight_icao", "linked_flight_icao"),
    ("flight_category", "flight_category"),
    ("service_type", "service_type"),
    ("route", "route"),
    ("deice_flag", "deice_flag"),
    ("deice_stand", "deice_stand"),
    ("SOBT", "sobt"),
    ("TOBT", "tobt"),
    ("TTOT", "ttot"),
    ("CTOT", "ctot"),
    ("AOBT", "aobt"),
    ("ATOT", "atot"),
    ("timeline_status", "timeline_status"),
    ("departure_punctuality_min", "departure_punctuality_min"),
    ("taxi_out_additional_min", "taxi_out_additional_min"),
    ("ctot_slot_adherence", "ctot_slot_adherence"),
    ("takeoff_prediction_error_min", "takeoff_prediction_error_min"),
    ("offblock_prediction_error_min", "offblock_prediction_error_min"),
)

PROCESSED_ACDM_ARRIVAL: tuple[tuple[str, str], ...] = (
    ("operation_date", "operation_date"),
    ("airport_icao", "airport_icao"),
    ("flight_icao", "flight_icao"),
    ("airline_icao", "airline_icao"),
    ("counterpart_airport_icao", "counterpart_airport_icao"),
    ("aircraft_registration", "aircraft_registration"),
    ("aircraft_type", "aircraft_type"),
    ("domestic_international", "domestic_international"),
    ("stand", "stand"),
    ("gate", "gate"),
    ("runway", "runway"),
    ("flight_status", "flight_status"),
    ("linked_flight_icao", "linked_flight_icao"),
    ("flight_category", "flight_category"),
    ("service_type", "service_type"),
    ("FIR", "fir"),
    ("APP", "app"),
    ("ELDT", "eldt"),
    ("ALDT", "aldt"),
    ("SIBT", "sibt"),
    ("AIBT", "aibt"),
    ("timeline_status", "timeline_status"),
    ("arrival_punctuality_min", "arrival_punctuality_min"),
    ("actual_taxi_in_min", "actual_taxi_in_min"),
    ("fir_to_app_min", "fir_to_app_min"),
    ("final_approach_min", "final_approach_min"),
    ("landing_prediction_abs_error_min", "landing_prediction_abs_error_min"),
)

PROCESSED_FOIS_DEPARTURE: tuple[tuple[str, str], ...] = (
    ("출발일자", "dep_date"),
    ("출발공항", "dep_airport"),
    ("편명", "flight_no"),
    ("등록부호", "reg_no"),
    ("STD", "std"),
    ("사유", "reason"),
    ("원인대분류", "cause_major"),
    ("원인소분류", "cause_minor"),
    ("원인공정", "cause_process"),
    ("관여주체", "involved_party"),
)

PROCESSED_FOIS_ARRIVAL: tuple[tuple[str, str], ...] = (
    ("도착일자", "arr_date"),
    ("도착공항", "arr_airport"),
    ("편명", "flight_no"),
    ("등록부호", "reg_no"),
    ("STA", "sta"),
    ("사유", "reason"),
    ("원인대분류", "cause_major"),
    ("원인소분류", "cause_minor"),
    ("원인공정", "cause_process"),
    ("관여주체", "involved_party"),
)

PROCESSED_FLOW_MANAGEMENT: tuple[tuple[str, str], ...] = (
    # 실제 산출 CSV 헤더 기준(2026-07-21 실측) — DB스키마.md §9.6은 "기상세부분류"로 적었으나
    # 실제 헤더는 "기상대분류"이고, "원본파일"/"원본시트" 2개 컬럼이 문서에서 누락되어 있었다
    # (코드/실제 산출물이 기준, 스킬연동_레퍼런스.md §0). 스킬을 직접 재실행한 독립 기준선으로
    # 재검증 완료(원본데이터/데이터/코드리뷰 비교 2026-07-21) — `outputs/` 폴더의 기존 샘플
    # CSV는 이보다 오래된 스킬 버전 산출물이라 이 계약과 다르니(원본파일/원본시트 없음, 기상
    # 컬럼명 다름) 참조하지 않는다. DB스키마.md §9.6은 아직 이 갱신을 반영하지 못해 문서가
    # 뒤처져 있다(문서 갱신 필요).
    ("흐름관리ID", "flow_id"),
    ("원본파일", "source_file"),
    ("원본시트", "source_sheet"),
    ("원본순번", "source_seq"),
    ("기록일자", "record_date"),
    ("통보시각", "notify_time"),
    ("적용시작일시", "apply_start_dt"),
    ("적용종료일시", "apply_end_dt"),
    ("적용분", "apply_minutes"),
    ("익일시작보정", "next_day_adjusted"),
    ("발신기관", "sender"),
    ("수신기관", "receiver"),
    ("사유코드", "reason_code"),
    ("기상대분류", "wx_category"),
    ("MINIT", "minit"),
    ("MIT", "mit"),
    ("고도속도제한", "alt_speed_limit"),
    ("원본대상", "raw_destination"),
    ("원본항공로", "raw_route"),
    ("원본지점", "raw_fix"),
    ("대상공항", "target_airport"),
    ("대상FIR", "target_fir"),
    ("대상항공로", "target_route"),
    ("대상지점", "target_fix"),
    ("제외공항", "excluded_airport"),
    ("특수범위", "special_scope"),
    ("공간범위유형", "scope_type"),
    ("방향", "direction"),
    ("비고", "remarks"),
    ("CTOT비고", "ctot_note"),
    ("제한내용요약", "restriction_summary"),
    ("품질상태", "quality_status"),
)

PROCESSED_COLUMNS: dict[str, tuple[tuple[str, str], ...]] = {
    "processed_flight_data": PROCESSED_FLIGHT_DATA,
    "processed_acdm_departure": PROCESSED_ACDM_DEPARTURE,
    "processed_acdm_arrival": PROCESSED_ACDM_ARRIVAL,
    "processed_fois_departure": PROCESSED_FOIS_DEPARTURE,
    "processed_fois_arrival": PROCESSED_FOIS_ARRIVAL,
    "processed_flow_management": PROCESSED_FLOW_MANAGEMENT,
}

# --- raw_*_rows 7종 계약 컬럼 (DB스키마.md §3.2, §9.7 규칙 적용) ---
# ACDM은 공항마다 원본 컬럼명이 달라 최소 식별 컬럼만 typed로 두고 나머지는 extra_columns로 흡수한다(§3.2).

RAW_FLIGHT_ANALYSIS_ROWS: tuple[tuple[str, str], ...] = (
    ("DATE", "date"),
    ("CALLSIGN", "callsign"),
    ("SSR", "ssr"),
    ("DEPT", "dept"),
    ("DEST", "dest"),
    ("D_EOBT", "d_eobt"),
    ("EOBT", "eobt"),
    ("D_ATD", "d_atd"),
    ("ATD", "atd"),
    ("ENTRY_DATE", "entry_date"),
    ("ENTRY_TIME", "entry_time"),
    ("EXIT_DATE", "exit_date"),
    ("EXIT_TIME", "exit_time"),
    ("RFL", "rfl"),
    ("AFL", "afl"),
    ("XFL", "xfl"),
    ("CFL", "cfl"),
    ("FIR_ENROUTE", "fir_enroute"),
)

RAW_FLIGHT_SEARCH_ROWS: tuple[tuple[str, str], ...] = (
    ("DATE", "date"),
    ("CALLSIGN", "callsign"),
    ("SSR", "ssr"),
    ("REG NO", "reg_no"),
    ("OTHER", "other"),
)

RAW_ACDM_DEPARTURE_ROWS: tuple[tuple[str, str], ...] = (
    ("source_file", "source_file"),
    ("source_date", "source_date"),
    # flight_no/reg_no: 컬럼은 만들어 두되 현재 loaders.py(_build_acdm_raw_records)는 채우지
    # 않는다(공항마다 원본 헤더가 달라 이번 라운드는 시도하지 않음, DB스키마.md §3.2) — 값은
    # 항상 NULL이고 원본 전체는 extra_columns에 그대로 들어간다. 공항별 별칭 매핑을 추가하면
    # 스키마 변경 없이 loaders.py만 고치면 된다.
    ("편명", "flight_no"),
    ("등록부호", "reg_no"),
)

RAW_ACDM_ARRIVAL_ROWS: tuple[tuple[str, str], ...] = RAW_ACDM_DEPARTURE_ROWS

RAW_FOIS_DEPARTURE_ROWS: tuple[tuple[str, str], ...] = (
    # 논리명은 스킬 실제 코드(run_fois_preprocessing.py SOURCE_COLUMNS)의 원본 헤더 그대로 —
    # DB스키마.md §3.2의 "구분/지연시간" 표기는 요약이며 실제 헤더와 다르다(코드가 기준,
    # 스킬연동_레퍼런스.md §0).
    ("번호", "no"),
    ("운항구분", "category"),
    ("출발일자", "dep_date"),
    ("편명", "flight_no"),
    ("기종", "aircraft_type"),
    ("등록부호", "reg_no"),
    ("출발공항", "dep_airport"),
    ("STD", "std"),
    ("ATD", "atd"),
    ("출발지연시간원본", "delay_raw"),
    ("도착공항", "arr_airport"),
    ("도착일자", "arr_date"),
    ("STA", "sta"),
    ("ATA", "ata"),
    ("도착지연시간원본", "delay_raw2"),
    ("지연기준구분", "delay_basis_category"),
    ("사유", "reason"),
)

RAW_FOIS_ARRIVAL_ROWS: tuple[tuple[str, str], ...] = RAW_FOIS_DEPARTURE_ROWS

RAW_FLOW_MANAGEMENT_ROWS: tuple[tuple[str, str], ...] = (
    ("Seq", "seq"),
    ("Date", "date"),
    ("RTime", "rtime"),
    ("Sender", "sender"),
    ("Receiver", "receiver"),
    ("Reasons", "reasons"),
    ("Start", "start_dt"),
    ("End", "end_dt"),
    ("Run", "run"),
    ("MINIT", "minit"),
    ("MIT", "mit"),
    ("Level Capping & G/S", "level_capping_gs"),
    ("Destination", "destination"),
    ("Route", "route"),
    ("Fix", "fix"),
    ("Remarks", "remarks"),
    ("Dir", "dir"),
    ("CTOT/Note", "ctot_note"),
    ("CTOT Pub", "ctot_pub"),
)

RAW_TABLE_COLUMNS: dict[str, tuple[tuple[str, str], ...]] = {
    "raw_flight_analysis_rows": RAW_FLIGHT_ANALYSIS_ROWS,
    "raw_flight_search_rows": RAW_FLIGHT_SEARCH_ROWS,
    "raw_acdm_departure_rows": RAW_ACDM_DEPARTURE_ROWS,
    "raw_acdm_arrival_rows": RAW_ACDM_ARRIVAL_ROWS,
    "raw_fois_departure_rows": RAW_FOIS_DEPARTURE_ROWS,
    "raw_fois_arrival_rows": RAW_FOIS_ARRIVAL_ROWS,
    "raw_flow_management_rows": RAW_FLOW_MANAGEMENT_ROWS,
}

# --- 컬럼 상세 설명 매핑 (UI 마우스 오버 툴팁용) ---
COLUMN_DESCRIPTIONS: dict[str, str] = {
    # processed_flight_data / raw_flight_analysis_rows / raw_flight_search_rows
    "date": "운항 일자 (YYYY-MM-DD)",
    "callsign": "항공편 호출부호 (Callsign)",
    "ssr": "Secondary Surveillance Radar Code (레이더 트랜스폰더 코드)",
    "dept": "출발공항 ICAO 코드",
    "dest": "도착공항 ICAO 코드",
    "eobt": "EOBT - Estimated Off-Block Time (예정 출발 시각)",
    "f_type": "비행 규칙 (Flight Type - I:계기, V:시각 등)",
    "atd": "ATD - Actual Time of Departure (실제 출발/이륙 시각)",
    "teet": "TEET - Total Estimated Elapsed Time (총 예상 소요 비행시간)",
    "rfl": "RFL - Requested Flight Level (요청 비행 고도)",
    "afl": "AFL - Actual Flight Level (실제 비행 고도)",
    "xfl": "XFL - Exit Flight Level (관제 이양 고도)",
    "cfl": "CFL - Cleared Flight Level (허가 비행 고도)",
    "a_type": "항공기 기종 (Aircraft Type)",
    "line": "배정 항공로 (Airway Route Line)",
    "entry_fir": "FIR(비행정보구역) 진입 시점 공역명",
    "entry_datetime": "FIR 진입 일시",
    "exit_fir": "FIR 진출 시점 공역명",
    "exit_datetime": "FIR 진출 일시",
    "ext_route": "확장 비행 경로",
    "full_route": "전체 비행 경로",
    "fir_enroute": "비행 경로 상 거쳐가는 FIR 목록",
    "alt_dest": "교대 목적지 공항",
    "unique_id": "데이터 행 식별 고유 ID",
    "reg_no": "항공기 등록 기호",
    "other": "기타 비정형 비행 정보",

    # processed_acdm_departure & arrival
    "operation_date": "운항 일자 (operation_date)",
    "airport_icao": "공항 ICAO 코드 (airport_icao)",
    "flight_icao": "편명 ICAO 코드 (flight_icao)",
    "airline_icao": "항공사 ICAO 코드 (airline_icao)",
    "counterpart_airport_icao": "상대 공항 ICAO 코드 (counterpart_airport_icao)",
    "aircraft_registration": "항공기 등록 기호 (aircraft_registration)",
    "aircraft_type": "항공기 기종 (aircraft_type)",
    "domestic_international": "국내선(D) / 국제선(I) 구분",
    "stand": "주기장 번호 (stand)",
    "gate": "탑승구 번호 (gate)",
    "runway": "배정 활주로 (runway)",
    "flight_status": "항공편 상태 (flight_status)",
    "exception_status": "예외 상황 상태 (exception_status)",
    "linked_flight_icao": "연결된 편명 ICAO (linked_flight_icao)",
    "flight_category": "비행 카테고리 (flight_category)",
    "service_type": "서비스 형태 (service_type)",
    "route": "비행 경로 (route)",
    "deice_flag": "디아이싱(방빙) 적용 여부",
    "deice_stand": "디아이싱 주기장",
    "sobt": "SOBT - Scheduled Off-Block Time (예정 출발 시각)",
    "tobt": "TOBT - Target Off-Block Time (목표 블록아웃 시각)",
    "ttot": "TTOT - Target Take-Off Time (목표 이륙 시각)",
    "ctot": "CTOT - Calculated Take-Off Time (배정 이륙 시각)",
    "aobt": "AOBT - Actual Off-Block Time (실제 출발/푸시백 시각)",
    "atot": "ATOT - Actual Take-Off Time (실제 이륙 시각)",
    "timeline_status": "타임라인 처리 상태 (timeline_status)",
    "departure_punctuality_min": "출발 정시성 지연 분 (departure_punctuality_min)",
    "taxi_out_additional_min": "추가 지상 이동(Taxi-out) 소요 분",
    "ctot_slot_adherence": "CTOT 슬롯 준수 여부 (ctot_slot_adherence)",
    "takeoff_prediction_error_min": "이륙 시간 예측 오차 분 (takeoff_prediction_error_min)",
    "offblock_prediction_error_min": "블록아웃 시간 예측 오차 분 (offblock_prediction_error_min)",
    "fir": "진입 FIR 정보 (fir)",
    "app": "접근 관제 정보 (app)",
    "eldt": "ELDT - Estimated Landing Time (예상 착륙 시각)",
    "aldt": "ALDT - Actual Landing Time (실제 착륙 시각)",
    "sibt": "SIBT - Scheduled In-Block Time (예정 주기장 도착 시각)",
    "aibt": "AIBT - Actual In-Block Time (실제 주기장 도착 시각)",
    "arrival_punctuality_min": "도착 정시성 지연 분 (arrival_punctuality_min)",
    "actual_taxi_in_min": "실제 지상 이동(Taxi-in) 소요 분 (actual_taxi_in_min)",
    "fir_to_app_min": "FIR에서 APP까지 비행 소요 분 (fir_to_app_min)",
    "final_approach_min": "최종 접근 비행 소요 분 (final_approach_min)",
    "landing_prediction_abs_error_min": "착륙 시간 예측 절대 오차 분 (landing_prediction_abs_error_min)",

    # processed_fois_departure & arrival / raw_fois_departure_rows
    "dep_date": "출발 일자 (dep_date)",
    "dep_airport": "출발 공항 (dep_airport)",
    "arr_date": "도착 일자 (arr_date)",
    "arr_airport": "도착 공항 (arr_airport)",
    "flight_no": "편명 (flight_no)",
    "std": "STD - Scheduled Time of Departure (예정 출발시각)",
    "sta": "STA - Scheduled Time of Arrival (예정 도착시각)",
    "ata": "ATA - Actual Time of Arrival (실제 도착시각)",
    "reason": "지연/비정상 사유 내용 (reason)",
    "cause_major": "지연 원인 대분류 (cause_major)",
    "cause_minor": "지연 원인 소분류 (cause_minor)",
    "cause_process": "지연 원인 공정 (cause_process)",
    "involved_party": "지연 관여 주체 (involved_party)",
    "no": "순번 (no)",
    "category": "운항 구분 (category)",
    "aircraft_type": "항공기 기종 (aircraft_type)",
    "delay_raw": "출발 지연 시간 원본",
    "delay_raw2": "도착 지연 시간 원본",
    "delay_basis_category": "지연 기준 구분",

    # processed_flow_management / raw_flow_management_rows
    "flow_id": "흐름관리 지시서 식별 ID (flow_id)",
    "source_file": "원본 소스 파일명 (source_file)",
    "source_sheet": "원본 소스 시트명 (source_sheet)",
    "source_seq": "원본 소스 행 순번 (source_seq)",
    "record_date": "기록 일자 (record_date)",
    "notify_time": "흐름관리 통보 시각 (notify_time)",
    "apply_start_dt": "적용 시작 일시 (apply_start_dt)",
    "apply_end_dt": "적용 종료 일시 (apply_end_dt)",
    "apply_minutes": "적용 시간 - 분 (apply_minutes)",
    "next_day_adjusted": "익일 적용 보정 정보 (next_day_adjusted)",
    "sender": "발신 기관명 (sender)",
    "receiver": "수신 기관명 (receiver)",
    "reason_code": "흐름관리 사유 코드 (reason_code)",
    "wx_category": "기상 영향 대분류 (wx_category)",
    "minit": "MINIT - Minutes In Trail (시간 간격 통제 값)",
    "mit": "MIT - Miles In Trail (거리 간격 통제 값)",
    "alt_speed_limit": "고도 및 속도 제한 내용 (alt_speed_limit)",
    "raw_destination": "원본 목적지 정보 (raw_destination)",
    "raw_route": "원본 항공로 정보 (raw_route)",
    "raw_fix": "원본 통제 지점 정보 (raw_fix)",
    "target_airport": "대상 타겟 공항 ICAO (target_airport)",
    "target_fir": "대상 타겟 FIR(비행정보구역) (target_fir)",
    "target_route": "대상 타겟 항공로 (target_route)",
    "target_fix": "대상 타겟 지점 (target_fix)",
    "excluded_airport": "제한 제외 공항 (excluded_airport)",
    "special_scope": "특수 제한 범위 (special_scope)",
    "scope_type": "공간 제약 범위 유형 (scope_type)",
    "direction": "통제 적용 비행 방향 (direction)",
    "remarks": "일반 비고 설명 (remarks)",
    "ctot_note": "CTOT 배정 비고 (ctot_note)",
    "restriction_summary": "흐름 제한 내용 전체 요약",
    "quality_status": "데이터 품질 분석 상태",
    "seq": "순번 (seq)",
    "date": "기준 일자 (date)",
    "rtime": "수신 통보 시각 (rtime)",
    "reasons": "사유 목록 (reasons)",
    "start_dt": "통제 시작 시간",
    "end_dt": "통제 종료 시간",
    "run": "항공로/지점 통제 구분",
    "level_capping_gs": "고도 제한 및 Ground Stop 여부",
    "destination": "목적지 공항",
    "dir": "항공로 통제 방향",
    "ctot_pub": "CTOT 발행 시각 (ctot_pub)"
}
